"""initial schema

Revision ID: 76075756b1f9
Revises: 
Create Date: 2026-09-21 20:58:26.196015

"""

from alembic import op
import sqlalchemy as sa


revision = '76075756b1f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('inspection_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_inspection', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    op.create_index(op.f('ix_managers_site_id'), 'managers', ['site_id'], unique=False)
    op.create_table('video_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('frame_interval', sa.Integer(), nullable=True),
    sa.Column('max_frames', sa.Integer(), nullable=True),
    sa.Column('frames_analyzed', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('worker_count', sa.Integer(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('helmet_violations', sa.Integer(), nullable=True),
    sa.Column('vest_violations', sa.Integer(), nullable=True),
    sa.Column('other_violations', sa.Integer(), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('ppe_compliance', sa.Float(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('ppe_workers', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('compliance_level', sa.String(), nullable=True),
    sa.Column('category_scores', sa.JSON(), nullable=True),
    sa.Column('requirements_checked', sa.Integer(), nullable=True),
    sa.Column('compliant_count', sa.Integer(), nullable=True),
    sa.Column('non_compliant_count', sa.Integer(), nullable=True),
    sa.Column('not_verified_count', sa.Integer(), nullable=True),
    sa.Column('open_violations', sa.Integer(), nullable=True),
    sa.Column('overdue_inspections', sa.Integer(), nullable=True),
    sa.Column('evidence_available', sa.Integer(), nullable=True),
    sa.Column('score_basis', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessments_analysis_id'), 'compliance_assessments', ['analysis_id'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('requirement_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('evidence_meta', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_findings_analysis_id'), 'compliance_findings', ['analysis_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('operating_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('maintenance_status', sa.String(), nullable=True),
    sa.Column('nearby_worker_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_analysis_id'), 'equipment', ['analysis_id'], unique=False)
    op.create_table('hazards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_contribution', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('recommended_mitigation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazards_analysis_id'), 'hazards', ['analysis_id'], unique=False)
    op.create_table('insurance_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('exposure', sa.JSON(), nullable=True),
    sa.Column('claim_risk', sa.JSON(), nullable=True),
    sa.Column('open_incidents', sa.Integer(), nullable=True),
    sa.Column('incident_severity', sa.String(), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_assessments_analysis_id'), 'insurance_assessments', ['analysis_id'], unique=False)
    op.create_table('insurance_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('workers_involved', sa.JSON(), nullable=True),
    sa.Column('hazards', sa.JSON(), nullable=True),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('claim_risk', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_incidents_analysis_id'), 'insurance_incidents', ['analysis_id'], unique=False)
    op.create_table('monitoring_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('equipment_activity', sa.JSON(), nullable=True),
    sa.Column('environmental_conditions', sa.JSON(), nullable=True),
    sa.Column('site_conditions', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_events_analysis_id'), 'monitoring_events', ['analysis_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('manager_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('dedup_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_analysis_id'), 'notifications', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_notifications_manager_id'), 'notifications', ['manager_id'], unique=False)
    op.create_index(op.f('ix_notifications_site_id'), 'notifications', ['site_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('environmental_score', sa.Float(), nullable=True),
    sa.Column('equipment_score', sa.Float(), nullable=True),
    sa.Column('site_condition_score', sa.Float(), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('environmental_factors', sa.JSON(), nullable=True),
    sa.Column('equipment_factors', sa.JSON(), nullable=True),
    sa.Column('site_condition_factors', sa.JSON(), nullable=True),
    sa.Column('activity_factors', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_analysis_id'), 'risk_assessments', ['analysis_id'], unique=False)
    op.create_table('risk_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_reports_analysis_id'), 'risk_reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_risk_reports_created_at'), 'risk_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_reports_site_id'), 'risk_reports', ['site_id'], unique=False)
    op.create_table('safety_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_acknowledged', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_alerts_analysis_id'), 'safety_alerts', ['analysis_id'], unique=False)
    op.create_table('safety_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_safety_score', sa.Float(), nullable=True),
    sa.Column('overall_safety_level', sa.String(), nullable=True),
    sa.Column('ppe_score', sa.Float(), nullable=True),
    sa.Column('ppe_compliance_rate', sa.Float(), nullable=True),
    sa.Column('worker_safety_score', sa.Float(), nullable=True),
    sa.Column('worker_count', sa.Integer(), nullable=True),
    sa.Column('accident_zone_score', sa.Float(), nullable=True),
    sa.Column('ppe_factors', sa.JSON(), nullable=True),
    sa.Column('worker_factors', sa.JSON(), nullable=True),
    sa.Column('accident_factors', sa.JSON(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_assessments_analysis_id'), 'safety_assessments', ['analysis_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('ppe_status', sa.String(), nullable=True),
    sa.Column('missing_ppe', sa.JSON(), nullable=True),
    sa.Column('detected_ppe', sa.JSON(), nullable=True),
    sa.Column('is_present', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_analysis_id'), 'workers', ['analysis_id'], unique=False)
    op.create_table('claim_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('documentation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['insurance_incidents.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_records_analysis_id'), 'claim_records', ['analysis_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('risk_assessment_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('hazard_type', sa.String(), nullable=True),
    sa.Column('related_hazard_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_analysis_id'), 'recommendations', ['analysis_id'], unique=False)
    op.create_table('risk_assessment_hazards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('risk_assessment_id', sa.String(), nullable=False),
    sa.Column('hazard_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_violations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_contribution', sa.Float(), nullable=True),
    sa.Column('recommended_mitigation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_violations_analysis_id'), 'safety_violations', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_violations_analysis_id'), table_name='safety_violations')
    op.drop_table('safety_violations')
    op.drop_table('risk_assessment_hazards')
    op.drop_index(op.f('ix_recommendations_analysis_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_claim_records_analysis_id'), table_name='claim_records')
    op.drop_table('claim_records')
    op.drop_index(op.f('ix_workers_analysis_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_safety_assessments_analysis_id'), table_name='safety_assessments')
    op.drop_table('safety_assessments')
    op.drop_index(op.f('ix_safety_alerts_analysis_id'), table_name='safety_alerts')
    op.drop_table('safety_alerts')
    op.drop_index(op.f('ix_risk_reports_site_id'), table_name='risk_reports')
    op.drop_index(op.f('ix_risk_reports_created_at'), table_name='risk_reports')
    op.drop_index(op.f('ix_risk_reports_analysis_id'), table_name='risk_reports')
    op.drop_table('risk_reports')
    op.drop_index(op.f('ix_risk_assessments_analysis_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_notifications_site_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_manager_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_analysis_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_monitoring_events_analysis_id'), table_name='monitoring_events')
    op.drop_table('monitoring_events')
    op.drop_index(op.f('ix_insurance_incidents_analysis_id'), table_name='insurance_incidents')
    op.drop_table('insurance_incidents')
    op.drop_index(op.f('ix_insurance_assessments_analysis_id'), table_name='insurance_assessments')
    op.drop_table('insurance_assessments')
    op.drop_index(op.f('ix_hazards_analysis_id'), table_name='hazards')
    op.drop_table('hazards')
    op.drop_index(op.f('ix_equipment_analysis_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_compliance_findings_analysis_id'), table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_compliance_assessments_analysis_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_table('zones')
    op.drop_table('video_analyses')
    op.drop_index(op.f('ix_managers_site_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_table('managers')
    op.drop_table('inspection_records')
    op.drop_table('compliance_requirements')
    op.drop_table('sites')
    op.drop_table('projects')
    # ### end Alembic commands ###